name: Demo CI
on:
  push:
    branches:
      - basic-ci

jobs:
  build:
    name: Build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Print Info
        run: echo "CI Triggered"
